/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffWorkloadRouteImport } from './routes/staff-workload'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const StaffWorkloadRoute = StaffWorkloadRouteImport.update({
  id: '/staff-workload',
  path: '/staff-workload',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/escalations': typeof EscalationsRoute
  '/guest': typeof GuestRoute
  '/hotel': typeof HotelRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/platform': typeof PlatformRoute
  '/properties': typeof PropertiesRoute
  '/staff-workload': typeof StaffWorkloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/escalations': typeof EscalationsRoute
  '/guest': typeof GuestRoute
  '/hotel': typeof HotelRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/platform': typeof PlatformRoute
  '/properties': typeof PropertiesRoute
  '/staff-workload': typeof StaffWorkloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/escalations': typeof EscalationsRoute
  '/guest': typeof GuestRoute
  '/hotel': typeof HotelRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/platform': typeof PlatformRoute
  '/properties': typeof PropertiesRoute
  '/staff-workload': typeof StaffWorkloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/escalations'
    | '/guest'
    | '/hotel'
    | '/login'
    | '/my-tasks'
    | '/platform'
    | '/properties'
    | '/staff-workload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/escalations'
    | '/guest'
    | '/hotel'
    | '/login'
    | '/my-tasks'
    | '/platform'
    | '/properties'
    | '/staff-workload'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/escalations'
    | '/guest'
    | '/hotel'
    | '/login'
    | '/my-tasks'
    | '/platform'
    | '/properties'
    | '/staff-workload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  EscalationsRoute: typeof EscalationsRoute
  GuestRoute: typeof GuestRoute
  HotelRoute: typeof HotelRoute
  LoginRoute: typeof LoginRoute
  MyTasksRoute: typeof MyTasksRoute
  PlatformRoute: typeof PlatformRoute
  PropertiesRoute: typeof PropertiesRoute
  StaffWorkloadRoute: typeof StaffWorkloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-workload': {
      id: '/staff-workload'
      path: '/staff-workload'
      fullPath: '/staff-workload'
      preLoaderRoute: typeof StaffWorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  EscalationsRoute: EscalationsRoute,
  GuestRoute: GuestRoute,
  HotelRoute: HotelRoute,
  LoginRoute: LoginRoute,
  MyTasksRoute: MyTasksRoute,
  PlatformRoute: PlatformRoute,
  PropertiesRoute: PropertiesRoute,
  StaffWorkloadRoute: StaffWorkloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
